name: Deployment
on:
  push:
    branches:
      - main #for diffrent environmental variables defoined
      - dev
env: #WHen environmental variable is defined at workflow level it is avialble for all jobs
  MONGODB_DB_NAME: gha-demo #name for the database
jobs:
  test:
    env: 
      MONGODB_CLUSTER_ADDRESS: cluster0.15pwqcc.mongodb.net #address
      MONGODB_USERNAME: keshav #user Name #secrets can also be used ${{secrets.MONGODB_USERNAME}} ${{secrets.Value name used during creation}}
      MONGODB_PASSWORD: password #password # ${{secrets.MONGODB_PASSWORD}}
      PORT: 8080
    environment: testing # this is used for settings us varibale for various testing ,devlopment and production value in the github repo
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT #When in windows (poweshell as terminal) we have to use $env:NAME . This is place to get environment variables defined in the definition file accessable from within.
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME:${{env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |  
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"      
          # echo "MONGODB_USERNAME: $MONGODB_USERNAME" will not be avialble as it defined inside of previous job
